// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs_AuySshngbx84Zq-A8VHpCdIqZFdZ5U',
    appId: '1:626276960343:web:347d328a3dfbff8dc4fb12',
    messagingSenderId: '626276960343',
    projectId: 'taskify-dd431',
    authDomain: 'taskify-dd431.firebaseapp.com',
    storageBucket: 'taskify-dd431.appspot.com',
    measurementId: 'G-HG9G3WYW0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe82ku2uc96OlNHH9hDcdpRaOzbg_Xgm8',
    appId: '1:626276960343:android:4bb9291e64be6e06c4fb12',
    messagingSenderId: '626276960343',
    projectId: 'taskify-dd431',
    storageBucket: 'taskify-dd431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SlzwaYMFWrlWUY2AswkiHt_EbHLqMYQ',
    appId: '1:626276960343:ios:f0697c99ea5f6554c4fb12',
    messagingSenderId: '626276960343',
    projectId: 'taskify-dd431',
    storageBucket: 'taskify-dd431.appspot.com',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1SlzwaYMFWrlWUY2AswkiHt_EbHLqMYQ',
    appId: '1:626276960343:ios:8113397e40461743c4fb12',
    messagingSenderId: '626276960343',
    projectId: 'taskify-dd431',
    storageBucket: 'taskify-dd431.appspot.com',
    iosBundleId: 'com.example.taskify.RunnerTests',
  );
}
